# Mage outfit
- type: startingGear
  id: MageGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitKimono
    # # belt holds katana so satchel has the tools for sabotaging things
    # back: ClothingBackpackSatchelTools
    # mask: ClothingMaskNinja
    head: ClothingHeadHatWizard
  #   eyes: ClothingEyesVisorNinja
    gloves: ClothingHandsGlovesColorBlueIsolated
    outerClothing: ClothingOuterWizard
    shoes: ClothingShoesWizard
  #   id: AgentIDCard
  #   ears: ClothingHeadsetGrey
  #   pocket1: SpiderCharge
  #   pocket2: PinpointerStation
  #   belt: EnergyKatana
  #   suitstorage: YellowOxygenTankFilled
  # inhand:
  #   - JetpackBlackFilled

#Pierates

- type: startingGear
  id: PirateGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitPirate
    back: ClothingBackpackPirateFilled
    head: ClothingHeadBandBlack
    shoes: ClothingShoesBootsLaceup
    id: PiratePDA
    ears: ClothingHeadsetFreelance
    belt: ClothingBeltUtility
    pocket1: AppraisalTool
    innerClothingSkirt: ClothingUniformJumpsuitPirate
    satchel: ClothingBackpackPirateFilled
    duffelbag: ClothingBackpackPirateFilled

- type: startingGear
  id: PirateCaptainGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitPirate
    back: ClothingBackpackPirateFilled
    head: ClothingHeadHatPirate
    shoes: ClothingShoesBootsLaceup
    id: PiratePDA
    ears: ClothingHeadsetAltFreelancer
    belt: ClothingBeltUtility
    pocket1: AppraisalTool
    pocket2: EnergyCutlass
    outerClothing: ClothingOuterCoatPirate
  innerClothingSkirt: ClothingUniformJumpskirtColorLightBrown
  satchel: ClothingBackpackPirateFilled
  duffelbag: ClothingBackpackPirateFilled

- type: startingGear
  id: PirateFirstmateGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitPirate
    back: ClothingBackpackPirateFilled
    head: ClothingHeadHatPirateTricord
    shoes: ClothingShoesBootsLaceup
    id: PiratePDA
    ears: ClothingHeadsetFreelance
    belt: ClothingBeltUtility
    pocket1: AppraisalTool
    outerClothing: ClothingOuterCoatGentle
  innerClothingSkirt: ClothingUniformJumpsuitPirate
  satchel: ClothingBackpackPirateFilled
  duffelbag: ClothingBackpackPirateFilled
