- type: entity
  parent: BaseMachineCircuitboard
  id: AutodocCircuitboard
  name: "плата автодокументації машини"
  description: "Машинна друкована плата для автодокумента."
  components:
  - type: MachineBoard
    prototype: Autodoc
    requirements:
      Manipulator: 4
    materialRequirements:
      Cable: 3
      Steel: 10
    tagRequirements:
      BorgArm:
        Amount: 3
        ExamineName: "Borg Arm"
        DefaultPrototype: LeftArmBorg

- type: entity
  parent: AutodocCircuitboard
  id: AutodocSyndieCircuitboard
  suffix: Syndie
  components:
  - type: MachineBoard
    prototype: AutodocSyndie

- type: entity
  parent: BaseMachineCircuitboard
  id: OperatingTableCircuitboard
  name: "операційний стіл машинна дошка"
  description: "Машинна друкована плата для операційного столу."
  components:
  - type: MachineBoard
    prototype: OperatingTable
    materialRequirements:
      Cable: 3
      Silver: 2
      Steel: 4

- type: entity
  id: MedicalBiofabMachineBoard
  parent: BaseMachineCircuitboard
  name: "медична плата для машин з біотканини"
  description: "Машинна друкована плата для медичної біофабрики."
  components:
  - type: Sprite
    state: medical
  - type: MachineBoard
    prototype: MedicalBiofabricator
    requirements:
      MatterBin: 2
      Manipulator: 2