- type: job
  id: HeadOfPersonnel
  name: job-name-hop
  description: job-description-hop
  playTimeTracker: JobHeadOfPersonnel
  antagAdvantage: 6 # DeltaV - Reduced TC: Head of Staff
  requirements:
    - !type:DepartmentTimeRequirement
      department: Engineering
      time: 36000 # 10 hours
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 36000 # 10 hours
    - !type:DepartmentTimeRequirement
      department: Security
      time: 36000 # 10 hrs
    - !type:DepartmentTimeRequirement
      department: Command
      time: 36000 # 10 hours
  weight: 20 # Я не знаю за що цей параметр відповідає тому повернув як в оригіналі
  startingGear: HoPGear
  icon: "JobIconHeadOfPersonnel"
  requireAdminNotify: true
  supervisors: job-supervisors-captain
  canBeAntag: false
  access:
  - Command
  - HeadOfPersonnel
  - Bar
  - Service
  - Maintenance
  - Mail # Nyanotrasen - MailCarrier, see Resources/Prototypes/Nyanotrasen/Roles/Jobs/Cargo/mail-carrier.yml
  - Orders # DeltaV - Orders, see Resources/Prototypes/DeltaV/Access/cargo.yml Доступ до заказів
  - Janitor
  - Theatre
  - Kitchen
  - Chapel
  - Hydroponics
  - External
  - Cryogenics
  # I mean they'll give themselves the rest of the access levels *anyways*.
  # As of 15/03/23 they can't do that so here's MOST of the rest of the access levels.
  # Head level access that isn't their own was deliberately left out, get AA from the captain instead.
  # Delta V - fuck all of this HoP is a service role
  - Chemistry
  - Psychologist # DeltaV - Add Psychologist access 
  - Mantis # DeltaV - Psionic Mantis, see Resources/Prototypes/DeltaV/Access/epistemics.yml Доступ до кімнати Мантіса
  - Engineering
  - Research
  - Detective
  - Salvage
  - Security
#  - Brig # В білду дельти немає доступу бріга
  - Corpsman # DeltaV - added Corpsman access
  - Paramedic # DeltaV - Add Paramedic access
  - Lawyer
  - Cargo
  - Atmospherics
  - Medical
  - Boxer # DeltaV - Add Boxer access
  - Clown # DeltaV - Add Clown access
  - Library # DeltaV - Add Library access
  - Mime # DeltaV - Add Mime access
  - Musician # DeltaV - Add Musician access
  - Reporter # DeltaV - Add Reporter access
  - Zookeeper # DeltaV - Add Zookeeper access
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff
  - !type:AddComponentSpecial
    components:
    - type: PsionicBonusChance #Nyano - Summary: makes it more likely to become psionic.
      flatBonus: 0.025

- type: startingGear
  id: HoPGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitHoP
    back: ClothingBackpackHOPFilled
    shoes: ClothingShoesLeather # DeltaV - HoP needs something better than plebe shoes.
    head: ClothingHeadHatHopcap
    id: HoPPDA
    gloves: ClothingHandsGlovesHop
    ears: ClothingHeadsetAltCommand
    belt: BoxFolderClipboard
  innerClothingSkirt: ClothingUniformJumpskirtHoP
  satchel: ClothingBackpackSatchelHOPFilled
  duffelbag: ClothingBackpackDuffelHOPFilled
