- type: loadout
  id: LoadoutSecurityUniformGrey
  category: Jobs
  cost: 2
  exclusive: true
  jobWhitelist:
    - SecurityOfficer
    - SecurityCadet
    - Warden
  items:
    - ClothingUniformJumpsuitSecGrey

- type: loadout
  id: LoadoutSecurityMaskGasSwat
  category: Jobs
  cost: 2
  exclusive: true
  jobWhitelist:
    - Warden
    - HeadOfSecurity
  items:
    - ClothingMaskGasSwat

- type: loadout
  id: LoadoutSecurityShoesJackboots
  category: Jobs
  cost: 1
  jobWhitelist:
    - Detective
    - SecurityOfficer
    - SecurityCadet
    - Warden
    - HeadOfSecurity
  items:
    - ClothingShoesBootsJack
