- type: loadout
  id: LoadoutServiceClownUniformJesterAlt
  description: For the fool who knows their place.
  category: Jobs
  cost: 2
  exclusive: true
  jobWhitelist:
    - Clown
  items:
    - ClothingUniformJumpsuitJesterAlt

- type: loadout
  id: LoadoutServiceClownShoesJester
  description: For the fool who knows their place.
  category: Jobs
  cost: 1
  exclusive: true
  jobWhitelist:
    - Clown
  items:
    - ClothingShoesJester

- type: loadout
  id: LoadoutServiceClownHeadJesterHatAlt
  description: For the fool who knows their place.
  category: Jobs
  cost: 1
  exclusive: true
  jobWhitelist:
    - Clown
  items:
    - ClothingHeadHatJesterAlt

- type: loadout
  id: LoadoutServiceBartenderUniformPurple
  description: An alternate job equipment.
  category: Jobs
  cost: 2
  exclusive: true
  jobWhitelist:
    - Bartender
  items:
    - ClothingUniformJumpsuitBartenderPurple

- type: loadout
  id: LoadoutServiceBotanistUniformOveralls
  description: A rugged pair of overalls.
  category: Jobs
  cost: 2
  exclusive: true
  jobWhitelist:
    - Botanist
  items:
    - ClothingUniformOveralls

- type: loadout
  id: LoadoutServiceLawyerUniformBlueSuit
  description: A suit, very legal indeed.
  category: Jobs
  cost: 2
  exclusive: true
  jobWhitelist:
    - Lawyer
  items:
    - ClothingUniformJumpsuitLawyerBlue

- type: loadout
  id: LoadoutServiceLawyerUniformBlueSkirt
  description: A skirt, very legal indeed.
  category: Jobs
  cost: 2
  exclusive: true
  jobWhitelist:
    - Lawyer
  items:
    - ClothingUniformJumpskirtLawyerBlue

- type: loadout
  id: LoadoutServiceLawyerUniformRedSuit
  description: A suit, very legal indeed.
  category: Jobs
  cost: 2
  exclusive: true
  jobWhitelist:
    - Lawyer
  items:
    - ClothingUniformJumpsuitLawyerRed

- type: loadout
  id: LoadoutServiceLawyerUniformRedSkirt
  description: A skirt, very legal indeed.
  category: Jobs
  cost: 2
  exclusive: true
  jobWhitelist:
    - Lawyer
  items:
    - ClothingUniformJumpskirtLawyerRed

- type: loadout
  id: LoadoutServiceLawyerUniformPurpleSuit
  description: A suit, very legal indeed.
  category: Jobs
  cost: 2
  exclusive: true
  jobWhitelist:
    - Lawyer
  items:
    - ClothingUniformJumpsuitLawyerPurple

- type: loadout
  id: LoadoutServiceLawyerUniformPurpleSkirt
  description: A skirt, very legal indeed.
  category: Jobs
  cost: 2
  exclusive: true
  jobWhitelist:
    - Lawyer
  items:
    - ClothingUniformJumpskirtLawyerPurple

- type: loadout
  id: LoadoutServiceLawyerUniformGoodSuit
  description: A suit, very legal indeed.
  category: Jobs
  cost: 2
  exclusive: true
  jobWhitelist:
    - Lawyer
  items:
    - ClothingUniformJumpsuitLawyerGood

- type: loadout
  id: LoadoutServiceLawyerUniformGoodSkirt
  description: A skirt, very legal indeed.
  category: Jobs
  cost: 2
  exclusive: true
  jobWhitelist:
    - Lawyer
  items:
    - ClothingUniformJumpskirtLawyerGood

- type: loadout
  id: LoadoutServiceReporterUniformJournalist
  description: For the reporter on the case!
  category: Jobs
  cost: 2
  exclusive: true
  jobWhitelist:
    - Reporter
  items:
    - ClothingUniformJumpsuitJournalist

- type: loadout
  id: LoadoutServiceReporterUniformDetectivesuit
  description: Always reminds you of the one that got away...
  category: Jobs
  cost: 2
  exclusive: true
  jobWhitelist:
    - Reporter
  items:
    - ClothingUniformJumpsuitDetective

- type: loadout
  id: LoadoutServiceReporterUniformDetectiveskirt
  description: Always reminds you of the one that got away...
  category: Jobs
  cost: 2
  exclusive: true
  jobWhitelist:
    - Reporter
  items:
    - ClothingUniformJumpskirtDetective
