- type: gameMapPool
  id: DefaultMapPool
  maps:
  - Box #50-∞
  - Glacier #15-70
  - Rad #35-∞
  - Atlas #5-20
  - Cluster #10-35
  - Omega #10-35
  - Reach #0-7
  - Gax #10-45
  - Meta #50-∞
  - Packed #5-40
  - Shoukou #0-60
  - Asterisk #0-60
  - Pebble #0-30
  - ParkStation #5-20
  - Aspid #0-70
  - Arena #30-80
  - Bagel #40-76
  - Cog #35-70
  - Hammurabi #50-∞
  - Saltern #0-35
  - Core #30-60
  - Lighthouse #15-55
  - Train #10-50
  - Submarine #60-∞
  - Edge #10-80
  - Oasis #70-∞
  - Fland #70-∞
  - Tortuga #50-∞
  - Marathon #35-70
  - TheHive #30-80
  - Origin #50-∞
  - Europa #0-30
  - Lambda #30 - 75
