- type: gameMapPool
  id: DefaultMapPool
  maps:
#PIRATE START
  - Atlas
  - Aspid
  - Bagel
  # - Barratry
  - Box
  - Cluster
  - Core
  - Fland
  - Marathon
  - Meta
  - Omega
  - Oasis
  - Origin
  - Saltern
  - Packed
  - Reach
  - Europa
#PIRATE END
# DeltaV
  - Arena
  - Asterisk
  - Edge
  - Hammurabi
  - Lighthouse
  - Pebble
  - Shoukou
  - Tortuga
  - TheHive
  - Submarine
