- type: job
  id: Magistrate
  name: "Магістрат"
  description: "Забезпечення дотримання космічного права, відстоювання справедливості і законності, проведення слухань і судових процесів, дотримання СОП, забезпечення дотримання командуванням космічного права."
  playTimeTracker: JobMagistrate
  requirements:
    - !type:CharacterDepartmentTimeRequirement
      department: Command
      min: 54000 # 15 hours
    - !type:CharacterDepartmentTimeRequirement
      department: Security
      min: 54000 # 15 hours
  weight: 20
  startingGear: MagistrateGear
  icon: "JobIconMagistrate"
  requireAdminNotify: true
  joinNotifyCrew: true
  supervisors: job-supervisors-centcom
  canBeAntag: false
  access:
  - Security
  - Brig
  - External
  - Cryogenics
  - Maintenance
  - Detective
  - Corpsman
  - Command
  - CentralCommand
  - Magistrate
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff

- type: startingGear
  id: MagistrateGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitMagistrate
    shoes: ClothingShoesLeather
    gloves: ClothingHandsGlovesColorWhite
    id: CentcomPDA
    ears: ClothingHeadsetMagistrate
    pocket1: UniqueMagistrateLockerTeleporter
