- type: job
  id: NanotrasenRepresentative
  name: "Представник Нанотрасен"
  description: "Представляти NT, надсилати їм звіти про ситуацію на станції, інформувати керівників про все, що їм накаже CentCom."
  playTimeTracker: JobNanotrasenRepresentative
  requirements:
    - !type:DepartmentTimeRequirement
      department: Command
      min: 54000 # 15 hours
  weight: 20
  startingGear: NanotrasenRepresentativeGear
  icon: "JobIconNanotrasenRepresentative"
  requireAdminNotify: true
  joinNotifyCrew: true
  supervisors: job-supervisors-centcom
  canBeAntag: false
  access:
  - CentralCommand
  - Brig
  - External
  - Cryogenics
  - Maintenance
  - Engineering
  - Medical
  - Research
  - Command
  - NanotrasenRepresentative
  - Lawyer
  - Cargo
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff

- type: startingGear
  id: NanotrasenRepresentativeGear
  equipment:
    shoes: ClothingShoesColorBlack
    id: CentcomPDA
    jumpsuit: ClothingUniformJumpsuitNanotrasenRepresentative
    ears: ClothingHeadsetCentCom
    pocket1: UniqueNanorepLockerTeleporter
