- type: job
  id: DeathSquad
  name: "ім'я_роботи_загін_смерті"
  description: job-description-deathsquad
  playTimeTracker: JobDeathSquad
  setPreference: false
  startingGear: DeathSquadGear
  icon: "JobIconNanotrasen"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess
  access:
  - CentralCommand