- type: loadout
  id: LoadoutCommandHOSNeckMantle
  description: To really show who has the authority around here.
  category: Jobs
  cost: 2
  exclusive: true
  jobWhitelist:
    - HeadOfSecurity
  items:
    - ClothingNeckMantleHOS

- type: loadout
  id: LoadoutCommandHOSNeckCloak
  description: To truly show who has the authority around here.
  category: Jobs
  cost: 2
  exclusive: true
  jobWhitelist:
    - HeadOfSecurity
  items:
    - ClothingNeckCloakHos

- type: loadout
  id: LoadoutCommandHOSJumpsuitAlt
  description: An alternate job equipment.
  category: Jobs
  cost: 2
  exclusive: true
  jobWhitelist:
    - HeadOfSecurity
  items:
    - ClothingUniformJumpsuitHoSAlt

- type: loadout
  id: LoadoutCommandHOSJumpsuitBlue
  description: An alternate job equipment.
  category: Jobs
  cost: 2
  exclusive: true
  jobWhitelist:
    - HeadOfSecurity
  items:
    - ClothingUniformJumpsuitHoSBlue

- type: loadout
  id: LoadoutCommandHOSJumpsuitGrey
  description: An alternate job equipment.
  category: Jobs
  cost: 2
  exclusive: true
  jobWhitelist:
    - HeadOfSecurity
  items:
    - ClothingUniformJumpsuitHoSGrey

- type: loadout
  id: LoadoutCommandHOSJumpsuitParade
  description: A fancy uniform for a fancy officer, wonder what event they mey be attending.
  category: Jobs
  cost: 3
  exclusive: true
  jobWhitelist:
    - HeadOfSecurity
  items:
    - ClothingUniformJumpsuitHoSParadeMale

- type: loadout
  id: LoadoutCommandHOSJumpsuitFormal
  description: The outfit is quite fancy. I am curious where the wearer could be heading to justify such a stylish look.
  category: Jobs
  cost: 3
  exclusive: true
  jobWhitelist:
    - HeadOfSecurity
  items:
    - ClothingUniformJumpsuitHosFormal

- type: loadout
  id: LoadoutCommandHOSJumpskirtAlt
  description: An alternate job equipment.
  category: Jobs
  cost: 2
  exclusive: true
  jobWhitelist:
    - HeadOfSecurity
  items:
    - ClothingUniformJumpskirtHoSAlt

- type: loadout
  id: LoadoutCommandHOSJumpskirtParade
  description: A fancy uniform for a fancy officer, wonder what event they mey be attending.
  category: Jobs
  cost: 3
  exclusive: true
  jobWhitelist:
    - HeadOfSecurity
  items:
    - ClothingUniformJumpskirtHoSParadeMale

- type: loadout
  id: LoadoutCommandHOSJumpskirtFormal
  description: The outfit is quite fancy. I am curious where the wearer could be heading to justify such a stylish look.
  category: Jobs
  cost: 3
  exclusive: true
  jobWhitelist:
    - HeadOfSecurity
  items:
    - ClothingUniformJumpskirtHosFormal

- type: loadout
  id: LoadoutCommandHOSOuterWinter
  description: A warm coat for the cold of space.
  category: Jobs
  cost: 2
  jobWhitelist:
    - HeadOfSecurity
  items:
    - ClothingOuterWinterHoS

- type: loadout
  id: LoadoutCommandHOSOuterTrench
  description: A trench coat for the HOS.
  category: Jobs
  cost: 2
  jobWhitelist:
    - HeadOfSecurity
  items:
    - ClothingOuterCoatHoSTrench

- type: loadout
  id: LoadoutCommandHOSHatBeret
  description: A beret for the HOS.
  category: Jobs
  cost: 1
  jobWhitelist:
    - HeadOfSecurity
  items:
    - ClothingHeadHatBeretHoS

- type: loadout
  id: LoadoutCommandHOSHatHoshat
  description: The HOS's hat, pretty nice.
  category: Jobs
  cost: 1
  jobWhitelist:
    - HeadOfSecurity
  items:
    - ClothingHeadHatHoshat
