- type: antag
  id: Traitor
  name: "зрадник-звання"
  antagonist: true
  setPreference: true
  objective: roles-antag-syndicate-agent-objective
  requirements:
  - !type:OverallPlaytimeRequirement # DeltaV - Playtime requirement
    time: 86400 # DeltaV - 24 hours
