 # Shitmed Change Start
- type: entity
  id: BasePart
  parent: BaseItem
  name: "частина тіла"
  abstract: true
  components:
  - type: Damageable
    damageContainer: OrganicPart
  - type: BodyPart
  - type: SurgeryTool
    startSound:
      path: /Audio/Medical/Surgery/organ1.ogg
    endSound:
      path: /Audio/Medical/Surgery/organ2.ogg
  - type: Gibbable
  - type: ContainerContainer
    containers:
      bodypart: !type:Container
        ents: []
  - type: StaticPrice
    price: 100
  - type: Tag
    tags:
      - Trash
  - type: Destructible
    thresholds:
    - trigger:
        !type:DamageTypeTrigger
        damageType: Blunt
        damage: 100
      behaviors:
      - !type:GibPartBehavior { }
    - trigger:
        !type:DamageTypeTrigger
        damageType: Slash
        damage: 150
      behaviors:
      - !type:GibPartBehavior { }
    - trigger:
        !type:DamageTypeTrigger
        damageType: Heat
        damage: 200
      behaviors:
      - !type:SpawnEntitiesBehavior
        spawnInContainer: true
        spawn:
          Ash:
            min: 1
            max: 1
      - !type:BurnBodyBehavior { }
      - !type:PlaySoundBehavior
        sound:
          collection: MeatLaserImpact

- type: entity
  id: BaseTorso
  name: "тулуб"
  parent: BasePart
  abstract: true
  components:
  - type: BodyPart
    partType: Torso
    toolName: "a torso"
    containerName: "torso_slot"
  - type: ContainerContainer
    containers:
      torso_slot: !type:ContainerSlot {}

- type: entity
  id: BaseHead
  name: "голова"
  parent: BasePart
  abstract: true
  components:
  - type: BodyPart
    partType: Head
    toolName: "a head"
    vital: true
  - type: Input
    context: "ghost"
  - type: Tag
    tags:
      - Head

- type: entity
  id: BaseLeftArm
  name: "ліва рука"
  parent: BasePart
  abstract: true
  components:
  - type: BodyPart
    partType: Arm
    symmetry: Left
    toolName: "a left arm"

- type: entity
  id: BaseRightArm
  name: "права рука"
  parent: BasePart
  abstract: true
  components:
  - type: BodyPart
    partType: Arm
    symmetry: Right
    toolName: "a right arm"

- type: entity
  id: BaseLeftHand
  name: "ліва рука"
  parent: BasePart
  abstract: true
  components:
  - type: BodyPart
    partType: Hand
    symmetry: Left
    toolName: "a left hand"

- type: entity
  id: BaseRightHand
  name: "права рука"
  parent: BasePart
  abstract: true
  components:
  - type: BodyPart
    partType: Hand
    symmetry: Right
    toolName: "a right hand"

- type: entity
  id: BaseLeftLeg
  name: "ліва нога"
  parent: BasePart
  abstract: true
  components:
  - type: BodyPart
    partType: Leg
    symmetry: Left
    toolName: "a left leg"
  - type: MovementBodyPart

- type: entity
  id: BaseRightLeg
  name: "права нога"
  parent: BasePart
  abstract: true
  components:
  - type: BodyPart
    partType: Leg
    symmetry: Right
    toolName: "a right leg"
  - type: MovementBodyPart

- type: entity
  id: BaseLeftFoot
  name: "ліва нога"
  parent: BasePart
  abstract: true
  components:
  - type: BodyPart
    partType: Foot
    symmetry: Left
    toolName: "a left foot"

- type: entity
  id: BaseRightFoot
  name: "права нога"
  parent: BasePart
  abstract: true
  components:
  - type: BodyPart
    partType: Foot
    symmetry: Right
    toolName: "a right foot"

 # Shitmed Change End
